# Generated by Django 4.1 on 2023-02-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historys', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='memo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
