# Generated by Django 4.1 on 2023-02-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historys', '0003_alter_history_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='history_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
