# Generated by Django 4.1 on 2023-02-23 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historys', '0004_alter_history_history_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='user_id',
            new_name='fk_user',
        ),
    ]
