# Generated by Django 4.1 on 2023-02-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_id_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
