# Generated by Django 4.1 on 2023-02-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balacne',
            field=models.BigIntegerField(default=0),
        ),
    ]
