# Generated by Django 4.1 on 2023-02-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_balacne'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='balacne',
            new_name='balance',
        ),
    ]
